// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ParcialComputo3.Data;

namespace ParcialComputo3.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParcialComputo3.Models.Brand", b =>
                {
                    b.Property<int>("idBrand")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("nameBrand")
                        .HasColumnType("text");

                    b.HasKey("idBrand");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("ParcialComputo3.Models.Car", b =>
                {
                    b.Property<int>("idCar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("colorCar")
                        .HasColumnType("text");

                    b.Property<int>("idBrand")
                        .HasColumnType("integer");

                    b.Property<string>("modelCar")
                        .HasColumnType("text");

                    b.Property<string>("typeCar")
                        .HasColumnType("text");

                    b.Property<string>("yearCar")
                        .HasColumnType("text");

                    b.HasKey("idCar");

                    b.ToTable("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
